"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env (not committed to git)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local dev; set DEBUG=False in the Render environment.
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# In production set SECRET_KEY in the environment; the insecure fallback below
# is only for local development and is refused outright once DEBUG=False, so a
# misconfigured deploy fails fast instead of silently running on a key that's
# sitting in plain sight in this file.
_INSECURE_DEV_SECRET_KEY = 'django-insecure-!ek=y9w+pr*8_t3ixd3w)01k1!im=h@1+d6tm1ha94vw)=d6c6'
SECRET_KEY = os.environ.get('SECRET_KEY', _INSECURE_DEV_SECRET_KEY)
if not DEBUG and SECRET_KEY == _INSECURE_DEV_SECRET_KEY:
    raise ImproperlyConfigured(
        'SECRET_KEY environment variable must be set when DEBUG=False.'
    )

# Hosts allowed to serve this app. Render injects RENDER_EXTERNAL_HOSTNAME for
# the service's own URL; extra hosts can be added via ALLOWED_HOSTS (comma list).
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
RENDER_HOST = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_HOST:
    ALLOWED_HOSTS.append(RENDER_HOST)
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    # Local apps
    'accounts',
    'procurement',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves Django's own static files (admin CSS/JS) in production without a
    # separate web server. Must sit right after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Uses Supabase (PostgreSQL) when DB_HOST is set in .env;
# falls back to local SQLite otherwise so the project still runs without config.
if os.environ.get('DB_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {'sslmode': 'require'},
            # Reuse connections across requests instead of opening a fresh
            # SSL connection to the remote DB every time (the main cause of
            # slow login/registration). Safe with Supabase's session pooler.
            'CONN_MAX_AGE': 600,
            'CONN_HEALTH_CHECKS': True,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Cache
# Throttle/rate-limit counters live in the cache. By default Django uses a
# per-process in-memory cache, which is fine for development and a single-worker
# deployment. In production with multiple workers/instances, set REDIS_URL in
# .env (e.g. redis://127.0.0.1:6379/1) so every worker shares one counter and
# the login limit is enforced across the whole fleet.
if os.environ.get('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ['REDIS_URL'],
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'eprocurement-throttle',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Where `collectstatic` gathers files for WhiteNoise to serve in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Uploaded supplier documents
# Leading slash matters: file URLs are built with request.build_absolute_uri()
# from /api/... requests, so a relative 'media/' would resolve to /api/media/...
# (404). '/media/' resolves to the media route registered in config/urls.py.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Rate limiting (throttling) applied to EVERY endpoint:
    #  - anonymous callers are limited by IP, authenticated users by account.
    # The login route additionally enforces a much stricter 5-per-15-minutes
    # limit via accounts.throttling.LoginRateThrottle (see LoginView), and the
    # two registration routes enforce a 10-per-hour limit via
    # accounts.throttling.RegisterRateThrottle (see RegisterView /
    # SupplierRegisterView) to stop scripted mass account creation.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '240/min',
        'login': '5/15m',
        'register': '10/h',
    },
}

# JWT lifetimes
from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# CORS — allow the Vite dev frontend to call the API. In production add the
# deployed frontend URL via FRONTEND_URL (e.g. https://your-frontend.onrender.com).
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]
FRONTEND_URL = os.environ.get('FRONTEND_URL')
if FRONTEND_URL:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

# Vercel generates a fresh preview URL for every deployment
# (e.g. capstone-bidding-system-<hash>-<team>.vercel.app), so matching by exact
# origin breaks on each redeploy. Allow any of this project's Vercel URLs —
# both the production domain and the preview deployments — via a regex.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://capstone-bidding-system[\w-]*\.vercel\.app$',
]

# Trust the deployed origins for CSRF (Django admin login, etc.).
CSRF_TRUSTED_ORIGINS = []
if RENDER_HOST:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_HOST}')
if FRONTEND_URL:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)

# Respect Render's proxy so request.is_secure() / HTTPS redirects work correctly.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Transport-security hardening — gated on DEBUG=False so local HTTP development
# (sqlite, http://127.0.0.1:8000) is completely unaffected. Safe in production
# because SECURE_PROXY_SSL_HEADER above already makes request.is_secure() true
# for real HTTPS traffic through Render's proxy, so this won't redirect-loop.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True  # admin login session cookie, HTTPS only
    CSRF_COOKIE_SECURE = True     # admin login CSRF cookie, HTTPS only
    # Start conservative (1 day) rather than the usual 1-year recommendation —
    # HSTS is cached by the browser, so a mistake here is hard to undo quickly.
    # Raise this once the HTTPS setup has been running smoothly for a while.
    SECURE_HSTS_SECONDS = 60 * 60 * 24
