# Generated by Django 6.0.6 on 2026-06-13 09:07

import procurement.models
import procurement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='audited_financial_statements',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='authorization_letter',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_reference_letter',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='supplier',
            name='declaration_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='financial_statement_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='mayors_permit',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='mayors_permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='past_contracts',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='performance_certificates',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='philgeps_certificate',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='supplier',
            name='representative_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sec_dti_certificate',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_clearance_certificate',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_clearance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tin',
            field=models.CharField(blank=True, max_length=30, verbose_name='TIN'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='track_record_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='valid_id',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
    ]
