# Generated by Django 6.0.6 on 2026-06-13 09:37

import procurement.models
import procurement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_supplier_audited_financial_statements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='audited_financial_statements',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='authorization_letter',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_reference_letter',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='mayors_permit',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='past_contracts',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='performance_certificates',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='philgeps_certificate',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sec_dti_certificate',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_clearance_certificate',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='valid_id',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=procurement.models.supplier_doc_path, validators=[procurement.validators.validate_upload]),
        ),
    ]
