# Generated by Django 6.0.6 on 2026-06-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_alter_supplier_audited_financial_statements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='document_reviews',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='supplier',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='qualification_status',
            field=models.CharField(choices=[('waiting_admin_approval', 'Waiting Admin Approval'), ('needs_revision', 'Needs Revision'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='waiting_admin_approval', max_length=30),
        ),
    ]
