# Generated by Django 6.0.6 on 2026-06-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_supplier_admin_notes_supplier_document_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_head', 'Pending Head Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('awarded', 'Awarded'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
