# Generated by Django 6.0.6 on 2026-06-14 01:37

import procurement.models
import procurement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_project_reject_reason_project_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_budget_document',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.procurement_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='project',
            name='bid_evaluation_criteria',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.procurement_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='purchase_request',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.procurement_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_specifications',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.procurement_doc_path, validators=[procurement.validators.validate_upload]),
        ),
        migrations.AddField(
            model_name='project',
            name='terms_of_reference',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.procurement_doc_path, validators=[procurement.validators.validate_upload]),
        ),
    ]
