# Generated by Django 6.0.6 on 2026-06-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_project_approved_budget_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('project', 'supplier'), name='unique_bid_per_supplier_project'),
        ),
    ]
