# Generated by Django 6.0.6 on 2026-06-15 16:10

import procurement.models
import procurement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_alter_bid_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reference_image',
            field=models.FileField(blank=True, null=True, upload_to=procurement.models.procurement_image_path, validators=[procurement.validators.validate_image_upload]),
        ),
    ]
