# Generated by Django 6.0.6 on 2026-06-15 16:47

import django.db.models.deletion
import procurement.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_project_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accuracy_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='delivery_timeline',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bid',
            name='interest_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='model_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='quotation_document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='bid_documents/quotations/', validators=[procurement.validators.validate_bid_upload]),
        ),
        migrations.AddField(
            model_name='bid',
            name='scm_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='specification_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='supplier_compliance_doc',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='bid_documents/compliance_docs/', validators=[procurement.validators.validate_bid_upload]),
        ),
        migrations.AddField(
            model_name='bid',
            name='supplier_datasheet',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='bid_documents/supplier_datasheets/', validators=[procurement.validators.validate_bid_upload]),
        ),
        migrations.AddField(
            model_name='bid',
            name='supplier_product_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='bid_documents/product_images/', validators=[procurement.validators.validate_bid_upload]),
        ),
        migrations.AddField(
            model_name='bid',
            name='technical_document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='bid_documents/technical/', validators=[procurement.validators.validate_bid_upload]),
        ),
        migrations.AddField(
            model_name='bid',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BidAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='bid_documents/attachments/', validators=[procurement.validators.validate_bid_upload])),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='procurement.bid')),
            ],
            options={
                'db_table': 'bid_attachments',
            },
        ),
    ]
