# Generated by Django 6.0.6 on 2026-06-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_bid_reviewed_at_project_awarded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='document_reviews',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
