# Generated by Django 6.0.6 on 2026-06-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_bid_document_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bidding_period_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
