# Generated by Django 6.0.6 on 2026-06-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_project_bidding_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_period_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='document_reviews',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_head', 'Pending Head Approval'), ('needs_revision', 'Needs Revision'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('awarded', 'Awarded'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
